"""initial_schema

Revision ID: 8b914f90f1db
Revises: 170a83685ede
Create Date: 2026-08-21 18:29:34.162648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_ = (op, sa)




# revision identifiers, used by Alembic.
revision: str = '8b914f90f1db'
down_revision: Union[str, None] = '170a83685ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
